# Generated by Django 4.1.7 on 2023-04-08 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MenuPage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribers',
            new_name='Subscriber',
        ),
    ]
