# Generated by Django 4.1.7 on 2023-04-11 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_nmb_productinorder_col_vo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinorder',
            old_name='col_vo',
            new_name='nmb',
        ),
    ]
