# Generated by Django 4.1.7 on 2023-04-29 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_productinbasket_session_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinbasket',
            old_name='order',
            new_name='order_id',
        ),
    ]
