# Generated by Django 4.1.7 on 2023-04-29 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_rename_order_productinbasket_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinbasket',
            old_name='order_id',
            new_name='order',
        ),
    ]
