# Generated by Django 4.1.7 on 2023-04-29 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_rename_order_id_productinbasket_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinbasket',
            name='order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
